# infrastructure/cloudbuild.yaml - Google Cloud Build configuration
# Builds Docker images for each service and pushes to Google Artifact Registry.

steps:
  # --- Build Listener Service ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Listener'
    dir: 'services/listener'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/listener:latest'
      - '.'

  # --- Build Subscriber Service ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Subscriber'
    dir: 'services/subscriber'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/subscriber:latest'
      - '.'

  # --- Build Price Loader Service ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Price Loader'
    dir: 'services/price_loader'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/price-loader:latest'
      - '.'

  # --- Build Ratio Calculator Service ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Ratio Calculator'
    dir: 'services/ratio_calculator'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/ratio-calculator:latest'
      - '.'

  # --- Build PDF Summarizer Service ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build PDF Summarizer'
    dir: 'services/pdf_summarizer'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/pdf-summarizer:latest'
      - '.'

  # --- Build News Summarizer Service ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build News Summarizer'
    dir: 'services/news_summarizer'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/news-summarizer:latest'
      - '.'

# Images to push to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/listener'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/subscriber'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/price-loader'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/ratio-calculator'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/pdf-summarizer'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/profit-scout-repo/news-summarizer'
